### ISSUE TITLE
Incompatibile for "SilverStripe Grouped CMS Menu"

### ISSUE THREAD

**Issue by barry-bookinglive** [nglasl/silverstripe-descriptive#2]
This module doesn't appear to work in combination with...

https://github.com/silverstripe-australia/silverstripe-grouped-cms-menu

**Comment by nglasl** [comment]
This is because both modules implement their own custom menu template, and only one of them can actually be used. It would be possible to add support for both modules, and I think the best solution would be to create you own template that includes that best of both worlds. I'm pretty sure I have done that for a project once before and it worked well :)
